const TIP_OUTS = {
  ADD_NEW_TIP_OUT: 'ADD_NEW_TIP_OUT',
  EDIT_TIP_OUT: 'EDIT_TIP_OUT',
  DELETE_TIP_OUT: 'DELETE_TIP_OUT',
  ADD_PEOPLE_TO_CURRENT_TIP_OUT: 'ADD_PEOPLE_TO_CURRENT_TIP_OUT',
  DELETE_PERSON: 'DELETE_PERSON',
  UPDATE_PERSON: 'UPDATE_PERSON',

};

export default TIP_OUTS;
